version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      # - run:
      #     name: "Install Dependencies"
      #     command: |
      #       apt-get update
      #       apt-get -y install npm
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: "Run Tests"
          command: echo "Run any tests here."
      - run:
          name: "deploy the latest master"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config user.email "roush.kyle@gmail.com"

              npm run deploy
            fi
